server:
  port: 9200
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    #prefer-ip-address: true
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
spring:
  application:
    name: patient-service
logging:
  level:
    com.example.howtodoinjava: DEBUG
    
app:
  id: ${random.uuid}    