server:
  port: 9100
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    #prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
spring:
  profiles:
    active: production
  application:
    name: doctor-service
logging:
  level:
    com.example.howtodoinjava: DEBUG
    file : elk-example.log      
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
