server:
  port: 9100
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    #prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
spring:
  profiles:
    active: production
  application:
    name: doctor-service
      
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
logging:
  file: elk-example.log
  level:
    com.doctorapi: DEBUG
    